# Generated by Django 6.0.4 on 2026-04-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_id', models.IntegerField(unique=True)),
                ('Dept_name', models.CharField(max_length=50)),
                ('Dept_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fac_id', models.IntegerField(unique=True)),
                ('Fac_name', models.CharField(max_length=50)),
                ('Fac_Email', models.EmailField(max_length=254)),
                ('Fac_Mobile', models.BigIntegerField()),
                ('Fac_dept', models.CharField(choices=[('cse', 'CSE'), ('mech', 'MECH'), ('eee', 'EEE'), ('civil', 'CIVIL'), ('ece', 'ECE'), ('it', 'IT')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_id', models.IntegerField(unique=True)),
                ('Std_name', models.CharField(max_length=50)),
                ('Std_Email', models.EmailField(max_length=254)),
                ('Std_Age', models.BigIntegerField()),
                ('Std_year', models.IntegerField()),
                ('Std_place', models.CharField(max_length=50)),
            ],
        ),
    ]
